name = "bioherbvn"
# Ensures Pages Functions use a stable runtime baseline
compatibility_date = "2025-09-17"

# Enable Node.js compatibility layer (Node core APIs) across environments
compatibility_flags = ["nodejs_compat"]

[env.production]
compatibility_flags = ["nodejs_compat"]

[env.preview]
compatibility_flags = ["nodejs_compat"]
